# Generated by Django 3.1 on 2020-09-24 14:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_auto_20200828_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('app_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=64)),
                ('app_img_url', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription_Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_bill', models.IntegerField()),
                ('month_bill', models.IntegerField()),
                ('year_bill', models.IntegerField()),
                ('app_id', models.ForeignKey(db_column='app_id', on_delete=django.db.models.deletion.CASCADE, to='subscription.application')),
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'unique_together': {('email', 'app_id')},
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(choices=[('W', 'week'), ('M', 'month'), ('Y', 'year'), ('L', 'life_time')], default='M', max_length=1)),
                ('bill', models.IntegerField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField(null=True)),
                ('created_at', models.DateTimeField()),
                ('app_id', models.ForeignKey(db_column='app_id', on_delete=django.db.models.deletion.CASCADE, to='subscription.application')),
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'unique_together': {('email', 'app_id')},
            },
        ),
    ]
