# Generated by Django 3.1 on 2020-09-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_name',
            field=models.CharField(max_length=128),
        ),
    ]
