# Generated by Django 3.1 on 2020-10-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20201002_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_name',
            field=models.CharField(max_length=256),
        ),
    ]
