# Generated by Django 3.1 on 2020-08-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('cellphone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
