# Generated by Django 3.1 on 2020-08-23 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=45)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
