# Generated by Django 3.1 on 2020-09-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200828_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
